### ISSUE TITLE
UPDATING SITE VIA API ON FIRST SUBMISSION TIMES OUT ( RETURNS 504 GATEWAY TIME OUT)

### ISSUE THREAD

**Issue by sserurich** [airqo-platform/AirQo-api#710] opened 2022-02-08 14:55 UTC
**What were you trying to achieve?**
To update site meta data using the api.
On first submission it displays this error below
![image](https://user-images.githubusercontent.com/8258229/153011824-f49e602f-578c-49bf-b7b6-46f2ff6756a7.png)
however when you re-submit it gives expected values

**What are the expected results?**
Irrespective of whether it's the first time a request is made or second or third, the sites info should be updated and success results like this returned
![image](https://user-images.githubusercontent.com/8258229/153012059-0e033388-9308-4f5c-9c3a-71685c91a843.png)

**What are the received results?**

**What are the steps to reproduce the issue?**
 Run the update api request in post man (PUT)
 https://platform.airqo.net/api/v1/devices/sites/refresh?tenant=airqo&generated_name=site_119
**In what environment did you encounter the issue?**
 - OS: windows 10
 - using postman rest api client

**Additional context**
Any other information you would like to share?

**Comment by Baalmart** [comment] 2022-02-09 06:10
Thanks for raising this issue @sserurich ....
Unfortunately, I am unable to reproduce this issue right now.

Also. a 504 error is usually not something that can easily be fixed, just requires a fix by the web server or the proxies we are trying to get access through. I will let @NoahNsimbe and @123MwanjeMike spearhead the investigations into this.

**Comment by Baalmart** [comment] 2023-04-20 05:19
Hi @sserurich ,

-  is this issue still present?
- Also, we decoupled the road metadata API for road distances since it was taking a long time to return results. So the refresh only refreshes the other details except the road metadata. You can follow up with @NoahNsimbe on this.
- I am also keen to learn of any comments from @123MwanjeMike

**Comment by 123MwanjeMike** [comment] 2023-04-20 06:08
> Hi @sserurich ,
> 
>     * is this issue still present?
> 
>     * Also, we decoupled the road metadata API for road distances since it was taking a long time to return results. So the refresh only refreshes the other details except the road metadata. You can follow up with @NoahNsimbe on this.
> 
>     * I am also keen to learn of any comments from @123MwanjeMike

Hi @Baalmart , I think we can close this issue.
I trust this was resolved

**Closed** 2024-09-13 21:17 UTC
